services:
  - type: web
    name: csv-product-importer-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: RENDER_SERVICE_URL
        value: https://csv-product-importer-api.onrender.com
    healthCheckPath: /health

